# Generated by Django 5.0.4 on 2024-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
